--How many total orders (order_id) exist?
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM TRAIN;

--Total sales per sub-category?
SELECT SUM(SALES) AS TOTAL_SALES,
SUB_CATEGORY FROM TRAIN
GROUP BY SUB_CATEGORY
ORDER BY TOTAL_SALES DESC; 

--How many customers (customer_id) exist?
SELECT COUNT(DISTINCT (CUSTOMER_ID)) AS TOTAL_CUSTOMERS FROM TRAIN;

--Total Regions / States / Cities
SELECT COUNT(DISTINCT(REGION)) AS REGIONS,
       COUNT(DISTINCT(STATE)) AS STATES,
	   COUNT(DISTINCT(CITY)) AS CITIES FROM TRAIN;
