--What is the date range (order_date) of orders?
SELECT MIN(ORDER_DATE) FIRST_ORDER_DATE,
       MAX(ORDER_DATE) LAST_ORDER_DATE FROM TRAIN;

--Monthly Sales Trend
SELECT TO_CHAR(ORDER_DATE,'MONTH') AS MONTHS,
SUM(SALES) AS TOTAL_SALES FROM TRAIN
GROUP BY TO_CHAR(ORDER_DATE,'MONTH')
ORDER BY TOTAL_SALES DESC;

--Orders per Month
SELECT TO_CHAR(ORDER_DATE,'MONTH') AS MONTHS,
COUNT(DISTINCT(ORDER_ID)) AS ORDERS  FROM TRAIN
GROUP BY TO_CHAR(ORDER_DATE,'MONTH')
ORDER BY ORDERS DESC;

--Average Order Value per Month
SELECT AVG(SALES) AS AVG_SALES,
TO_CHAR(ORDER_DATE,'MONTH') AS MONTHS FROM TRAIN
GROUP BY TO_CHAR(ORDER_DATE,'MONTH')
ORDER BY AVG_SALES DESC;
