--Total sales per sub-category?
SELECT SUM(SALES) AS TOTAL_SALES,
SUB_CATEGORY FROM TRAIN
GROUP BY SUB_CATEGORY
ORDER BY TOTAL_SALES DESC; 

--Total Sales per Category
SELECT SUM(SALES) AS TOTAL_SALES,
CATEGORY FROM TRAIN
GROUP BY CATEGORY
ORDER BY TOTAL_SALES DESC; 

--Top 10 Customers by Total Sales
SELECT SUM(SALES) AS TOTAL_SALES,
CUSTOMER_ID FROM TRAIN
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_SALES DESC
LIMIT 10;

--Segment-wise Sales Comparison
SELECT SEGMENT, 
SUM(SALES) AS TOTAL_SALES FROM TRAIN
GROUP BY SEGMENT
ORDER BY TOTAL_SALES DESC;