--Orders per Ship Mode
SELECT COUNT(DISTINCT(ORDER_ID)) AS TOTAL_ORDERS,
SHIP_MODE FROM TRAIN 
GROUP BY SHIP_MODE
ORDER BY TOTAL_ORDERS DESC;

--Average Delivery Time per Ship Mode
SELECT ROUND(AVG(SHIP_DATE-ORDER_DATE)) AS AVG_DELIVERY_TIME,
SHIP_MODE FROM TRAIN 
GROUP BY SHIP_MODE;

--Top Performing Region & Category
SELECT SUM(SALES) AS TOTAL_SALES,
REGION,CATEGORY FROM TRAIN 
GROUP BY REGION, CATEGORY
ORDER BY TOTAL_SALES DESC;

--Does faster delivery lead to higher sales value?
SELECT SUM(SALES) AS TOTAL_SALES ,
       COUNT(DISTINCT(ORDER_ID)) AS TOTAL_ORDERS ,
	   ROUND((SUM(SALES)/COUNT(DISTINCT(ORDER_ID))),2) AS AVG_SALES_PER_ORDER,
	   SHIP_MODE FROM TRAIN 
GROUP BY SHIP_MODE
ORDER BY AVG_SALES_PER_ORDER DESC;