DROP TABLE IF EXISTS TRAIN;
CREATE TABLE TRAIN(
 Row_ID	INT,
 Order_ID VARCHAR(20), 
 Order_Date DATE, 	
 Ship_Date DATE, 	
 Ship_Mode VARCHAR(50),
 Customer_ID VARCHAR(50),
 Customer_Name VARCHAR(100),	
 Segment VARCHAR(50),	
 Country VARCHAR(100),	
 City VARCHAR(100),
 State VARCHAR(100),	
 Postal_Code INT,
 Region	VARCHAR(10),
 Product_ID VARCHAR(100),	
 Category VARCHAR(100),
 Sub_Category VARCHAR(100),
 Sales NUMERIC(10,5)
); 

SELECT*FROM TRAIN;
SELECT * FROM TRAIN 
WHERE  Row_ID IS NULL
 OR 
 Order_ID IS NULL
 OR
 Order_Date IS NULL
 OR 
 Ship_Date IS NULL
 OR
 Ship_Mode IS NULL
 OR
 Customer_ID IS NULL
 OR
 Customer_Name IS NULL
 OR
 Segment IS NULL
 OR
 Country IS NULL
 OR
 City IS NULL
 OR 
 State IS NULL
 OR
 Postal_Code IS NULL
 OR
 Region IS NULL
 OR
 Product_ID IS NULL
 OR
 Category IS NULL
 OR 
 Sub_Category IS NULL
 OR
 Sales IS NULL;

UPDATE TRAIN
SET Postal_Code=0
WHERE Postal_Code IS NULL;

--Retail Insights
SELECT*FROM TRAIN;
--How many total orders (order_id) exist?
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM TRAIN;

--Total sales per sub-category?
SELECT SUM(SALES) AS TOTAL_SALES,
SUB_CATEGORY FROM TRAIN
GROUP BY SUB_CATEGORY
ORDER BY TOTAL_SALES DESC; 

--What is the date range (order_date) of orders?
SELECT MIN(ORDER_DATE) FIRST_ORDER_DATE,
       MAX(ORDER_DATE) LAST_ORDER_DATE FROM TRAIN;

--How many customers (customer_id) exist?
SELECT COUNT(DISTINCT (CUSTOMER_ID)) AS TOTAL_CUSTOMERS FROM TRAIN;

--Total Regions / States / Cities
SELECT COUNT(DISTINCT(REGION)) AS REGIONS,
       COUNT(DISTINCT(STATE)) AS STATES,
	   COUNT(DISTINCT(CITY)) AS CITIES FROM TRAIN;
 
--Monthly Sales Trend
SELECT TO_CHAR(ORDER_DATE,'MONTH') AS MONTHS,
SUM(SALES) AS TOTAL_SALES FROM TRAIN
GROUP BY TO_CHAR(ORDER_DATE,'MONTH')
ORDER BY TOTAL_SALES DESC;

--Orders per Month
SELECT TO_CHAR(ORDER_DATE,'MONTH') AS MONTHS,
COUNT(DISTINCT(ORDER_ID)) AS ORDERS  FROM TRAIN
GROUP BY TO_CHAR(ORDER_DATE,'MONTH')
ORDER BY ORDERS DESC;

--Average Order Value per Month
SELECT AVG(SALES) AS AVG_SALES,
TO_CHAR(ORDER_DATE,'MONTH') AS MONTHS FROM TRAIN
GROUP BY TO_CHAR(ORDER_DATE,'MONTH')
ORDER BY AVG_SALES DESC;

--Total Sales per Category
SELECT SUM(SALES) AS TOTAL_SALES,
CATEGORY FROM TRAIN
GROUP BY CATEGORY
ORDER BY TOTAL_SALES DESC; 

--Top 10 Customers by Total Sales
SELECT SUM(SALES) AS TOTAL_SALES,
CUSTOMER_ID FROM TRAIN
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_SALES DESC
LIMIT 10;

--Segment-wise Sales Comparison
SELECT SEGMENT, 
SUM(SALES) AS TOTAL_SALES FROM TRAIN
GROUP BY SEGMENT
ORDER BY TOTAL_SALES DESC;

--Orders per Ship Mode
SELECT COUNT(DISTINCT(ORDER_ID)) AS TOTAL_ORDERS,
SHIP_MODE FROM TRAIN 
GROUP BY SHIP_MODE
ORDER BY TOTAL_ORDERS DESC;

--Average Delivery Time per Ship Mode
SELECT ROUND(AVG(SHIP_DATE-ORDER_DATE)) AS AVG_DELIVERY_TIME,
SHIP_MODE FROM TRAIN 
GROUP BY SHIP_MODE;

--Top Performing Region & Category
SELECT SUM(SALES) AS TOTAL_SALES,
REGION,CATEGORY FROM TRAIN 
GROUP BY REGION, CATEGORY
ORDER BY TOTAL_SALES DESC;

--Does faster delivery lead to higher sales value?
SELECT SUM(SALES) AS TOTAL_SALES ,
       COUNT(DISTINCT(ORDER_ID)) AS TOTAL_ORDERS ,
	   ROUND((SUM(SALES)/COUNT(DISTINCT(ORDER_ID))),2) AS AVG_SALES_PER_ORDER,
	   SHIP_MODE FROM TRAIN 
GROUP BY SHIP_MODE
ORDER BY AVG_SALES_PER_ORDER DESC;

--Which Region–Category combinations should the company focus on?
SELECT SUM(SALES) AS TOTAL_SALES, 
       COUNT(DISTINCT(ORDER_ID)) AS TOTAL_ORDERS,
	   REGION,CATEGORY FROM TRAIN
	   GROUP BY REGION,CATEGORY;